scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:4001' ]

  - job_name: 'config-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:8888' ]

  - job_name: 'eureka-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:8761' ]

  - job_name: 'event-service'
    metrics_path: '/events/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:9999' ]

  - job_name: 'account-service'
    metrics_path: '/accounts/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:10001' ]


