spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.security: DEBUG
