server:
  port: 4001

spring:
  cloud:
    gateway:
      routes:
        - id: accounts_route
          uri: ${ACCOUNT_ROUTE_URI:http://localhost:6000}
          predicates:
            - Path=/accounts/**


