spring:
  application:
    name: account-service
  profiles:
    active: dev
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  data:
    redis:
      host: redis-18796.c294.ap-northeast-1-2.ec2.redns.redis-cloud.com
      port: 18796
      password: oN7pR7PlYVYmp12LHGirQrqbMAQMenGY
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tixery_account
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write:
            timeout: 10000
          connection:
            timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST:http://localhost:4001}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 753083576806-ec8f2us12a5im0qv8kar8sfb9lg3mr8r.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 848995503880292
            client-secret: e0114f99c2536fa71d91f5adc08455b3


eureka:
  instance:
    hostname: localhost

#feign:
#  hystrix:
#    enabled: true

