spring:
  application:
    name: event-service
  profiles:
    active: dev
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: full
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write:
            timeout: 10000
          connection:
            timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
client:
  host: ${CLIENT_HOST:http://localhost:5173}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

eureka:
  instance:
    hostname: localhost
logging:
  level:
    org.springframework.security: DEBUG
